// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqMia_mihATTHnOAI-5Jpj-oGqBBZnMMI',
    appId: '1:278172301654:web:4def6f913606ad56733ef7',
    messagingSenderId: '278172301654',
    projectId: 'roadsafedb',
    authDomain: 'roadsafedb.firebaseapp.com',
    storageBucket: 'roadsafedb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV5R2BucQihuAF-7LPxp78-w066OSthaU',
    appId: '1:278172301654:android:936512ca292e0cfa733ef7',
    messagingSenderId: '278172301654',
    projectId: 'roadsafedb',
    storageBucket: 'roadsafedb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeeslTX31Lb2JvkLUGu8PFmiR_n5iKjqI',
    appId: '1:278172301654:ios:42259165922a5890733ef7',
    messagingSenderId: '278172301654',
    projectId: 'roadsafedb',
    storageBucket: 'roadsafedb.firebasestorage.app',
    iosBundleId: 'com.example.saferoad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeeslTX31Lb2JvkLUGu8PFmiR_n5iKjqI',
    appId: '1:278172301654:ios:42259165922a5890733ef7',
    messagingSenderId: '278172301654',
    projectId: 'roadsafedb',
    storageBucket: 'roadsafedb.firebasestorage.app',
    iosBundleId: 'com.example.saferoad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqMia_mihATTHnOAI-5Jpj-oGqBBZnMMI',
    appId: '1:278172301654:web:1c113e5409e9131e733ef7',
    messagingSenderId: '278172301654',
    projectId: 'roadsafedb',
    authDomain: 'roadsafedb.firebaseapp.com',
    storageBucket: 'roadsafedb.firebasestorage.app',
  );
}
