// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYyq0EmhNls3L361V1YJdPBfbkJ4OP7Gg',
    appId: '1:8415063511:web:a4dc93a190f611f461ef92',
    messagingSenderId: '8415063511',
    projectId: 'saferoad-643a9',
    authDomain: 'saferoad-643a9.firebaseapp.com',
    storageBucket: 'saferoad-643a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Ep_VLPYodlO8K5mc-DSqzJAKqpgtLUs',
    appId: '1:8415063511:android:d236d632a364344b61ef92',
    messagingSenderId: '8415063511',
    projectId: 'saferoad-643a9',
    storageBucket: 'saferoad-643a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBKcPsnod-1RrOag9Nlhur0YQcVxOOSvk',
    appId: '1:8415063511:ios:da1129f107e2ac8161ef92',
    messagingSenderId: '8415063511',
    projectId: 'saferoad-643a9',
    storageBucket: 'saferoad-643a9.firebasestorage.app',
    iosBundleId: 'com.example.saferoad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBKcPsnod-1RrOag9Nlhur0YQcVxOOSvk',
    appId: '1:8415063511:ios:da1129f107e2ac8161ef92',
    messagingSenderId: '8415063511',
    projectId: 'saferoad-643a9',
    storageBucket: 'saferoad-643a9.firebasestorage.app',
    iosBundleId: 'com.example.saferoad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYyq0EmhNls3L361V1YJdPBfbkJ4OP7Gg',
    appId: '1:8415063511:web:5c2d6f82945c894261ef92',
    messagingSenderId: '8415063511',
    projectId: 'saferoad-643a9',
    authDomain: 'saferoad-643a9.firebaseapp.com',
    storageBucket: 'saferoad-643a9.firebasestorage.app',
  );
}
